DB_PATH = "housekeeping_server.db"

PREINSTALLED_TASKS = [
    ("Mow gras", 182),
    ("Replace bed sheets", 14),
    ("Bathroom", 14),
    ("Toilets", 14),
    ("Kitchen cabinets outside", 30),
    ("Furniture living room", 14),
    ("Mop bathroom", 30),
    ("Mop toilets", 30),
    ("Oven", 30),
    ("Coffeemaker", 30),
    ("Shower", 60),
    ("Mop upstairs", 60),
    ("Laundromat cleaning program", 60),
    ("Cat litter", 91),
    ("Bedroom", 60),
    ("Fridge check dates and clean", 91),
    ("Mop living room", 91),
    ("Laundromat waste water", 91),
    ("Vacuum cleaner filter", 91),
    ("Windows outside", 91),
    ("Windows inside", 91),
    ("Car outside", 91),
    ("Car inside", 91),
    ("Dishwasher (filter, cleaning program, salt, rinse aid)", 91),
    ("Bathroom air filter", 182),
    ("Kitchen cabinets inside", 182),
    ("Bathroom cabinets", 182),
    ("Slats kitchen window", 182),
    ("Scrub cooktop", 182),
    ("Pantry check dates and clean", 182),
    ("Bathroom walls", 365),
    ("Doors", 365),
    ("Bathroom ground lines", 365),
    ("Kitchen extractor hood", 365),
    ("Bed baby", 14),
    ("Dryer maintenance", 30)
]
